export const column = [
  { key: '1', headerName: 'S.No', field: 'S.No', hide: false, width: 70 },
  // { key: '2', headerName: 'ID/code', field: 'id', hide: false, width: 300 },
  { key: '3', headerName: 'State Name', field: 'state', hide: false, width: 180 },
  { key: '4', headerName: 'Sub zone Name', field: 'subZone', hide: false, width: 120 },
  { key: '5', headerName: 'City Name', field: 'city', hide: false, width: 180 },
  { key: '6', headerName: 'Outlet Code', field: 'outletC', hide: false, width: 180 },
  { key: '7', headerName: 'Outlet Name', field: 'outletN', hide: false, width: 180 },
  { key: '8', headerName: 'Zomato Service Available', field: 'zomato', hide: false, width: 180 },
  { key: '9', headerName: 'Zomato ID', field: 'ZId', hide: false, width: 180 },
  { key: '10', headerName: 'Zomato Live Data', field: 'zLiveData', hide: false, width: 180 },
  { key: '11', headerName: 'Swiggy Service Available', field: 'swiggy', hide: false, width: 180 },
  { key: '12', headerName: 'Swiggy ID', field: 'swiggyId', hide: false, width: 180 },
  { key: '13', headerName: 'Swiggy Live Data', field: 'swiggyLiveData', hide: false, width: 180 },
  { key: '14', headerName: 'Dotpe Service Available', field: 'Dotpe', hide: false, width: 180 },
  { key: '15', headerName: 'Dotpe ID', field: 'dotpeId', hide: false, width: 180 },
  { key: '16', headerName: 'Dotpe Live Data', field: 'dotpeLiveData', hide: false, width: 180 },
  { key: '17', headerName: 'Email', field: 'email', hide: false, width: 180 },
  { key: '18', headerName: 'Latitude No', field: 'latitude', hide: false, width: 180 },
  { key: '19', headerName: 'Longitude No', field: 'longitude', hide: false, width: 180 },
  { key: '20', headerName: 'Restaurant Address', field: 'restaurantAddress', hide: false, width: 180 },
  { key: '21', headerName: 'Order Placing No', field: 'orderPlacingNo', hide: false, width: 180 },
  { key: '22', headerName: 'ORL CUG No', field: 'ORLCUGNo', hide: false, width: 180 },
  { key: '23', headerName: 'Contact ', field: 'contact', hide: false, width: 180 },
  { key: '24', headerName: 'Open Time', field: 'openTime', hide: false, width: 180 },
  { key: '25', headerName: 'Close Time', field: 'closeTime', hide: false, width: 180 },
  { key: '26', headerName: 'Outlet Opening Date', field: 'outletOpeningDate', hide: false, width: 180 },
  { key: '27', headerName: 'Profit Center', field: 'profitCenter', hide: false, width: 180 },
  { key: '28', headerName: 'Cost Center', field: 'costCenter', hide: false, width: 180 },
  { key: '29', headerName: 'Labour License No', field: 'labourLicenseNo', hide: false, width: 180 },
  { key: '30', headerName: 'Fire License No', field: 'fireLicenseNo', hide: false, width: 180 },
  { key: '31', headerName: 'Fire Extinguisher License No', field: 'fireExtinguisherLicenseNo', hide: false, width: 180 },
  { key: '32', headerName: 'FAASI License No', field: 'FAASILicenseNo', hide: false, width: 180 },
  { key: '33', headerName: 'Status', field: 'status', hide: false, width: 180 }
];
